In [65]:
import numpy as np

rng = np.random.default_rng()

n = 4

m = 2*np.ones((n,n),int)

def detGame(turn , token):
    # turn = who's turn
    # turn = 0 => User's turn // Player 0 
    # turn = 1 => Bot's turn // Player 1
    # token = the player's assigned token
    # token = 0 => Player can play 0
    # token = 1 => Player can play 1
    #ASSUME PLAYER WHO PICKS 0, WIN CON = DET = 0
    global m
    
    # User Case
    if(turn==0):
        print("\nStart of user's turn")
        print(m)
        i,j = userPick()
        print('User picks ',i,j)
        m[i-1,j-1] = token        

    # Bot Case
    elif(turn==1):
        print("\nStart of Bot's Turn")
        print(m)
        i,j = botPick()
        print("Computer picks",i+1,j+1)
        m[i,j] = token

    if(hasTwo(m)):
        detGame( (turn +1) % 2, (token +1) % 2 )
    else:
        print("\n end of game\n",m)
        if(np.linalg.det(m)==0):
            if(token==0):
                print(f"Player {turn} wins")
                return 0
            else:
                print(f"Player {(turn+1)%2} wins")
        else:
            #det = non zero
            if(token==1):
                print(f"Player {turn} wins")
            else:
                print(f"Player {(turn+1)%2} wins")






def userPick():
    print(f"Pick row (1 to {n})")
    i = int(input())
    print(f"pick column (1 to {n})")
    j = int(input())
    #print('Human coordinates',i,j)
    if( 0<i<n+1 and 0<j<n+1 and m[i-1,j-1]==2 ):
        return i, j
    else:
        print("\nInvalid Choice")
        return userPick()

def botPick():
    i = rng.integers(0,n)
    j = rng.integers(0,n)
    if( m[i,j] != 2):
        return botPick()
    return i, j

def hasTwo(m):
    for x in range(0,n):
        for y in range(0,n):
            if( m[x,y] == 2 ):
                return True
    return False
                 


#case 1: User starts, and can play zero
detGame( 0 , 0)




Start of user's turn
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
Pick row (1 to 4)


ValueError: invalid literal for int() with base 10: ''

In [ ]:
#Test block
xd = 2*np.ones((n,n),int)
xd[0,1]=0
print(xd)
print(xd[0])

turn = 1
print(f"Player {(turn+1)%2} wins")


Approach 1: Play Randomly

In [264]:
import time
rng = np.random.default_rng()

n = 2

m = 2*np.ones((n,n),int)

def detGame(turn , token):
    # turn = who's turn
    # turn = 0 => User's turn // Player 0 
    # turn = 1 => Bot's turn // Player 1
    # token = the player's assigned token
    # token = 0 => Player can play 0
    # token = 1 => Player can play 1
    #ASSUME PLAYER WHO PICKS 0, WIN CON = DET = 0
    global m
    t=turn
    # User Case
    if(turn==0):
        print("\nStart of user's turn")
        print(m)
        i,j = botPick()
        print("User picks",i+1,j+1)
        m[i,j] = token     

    # Bot Case
    elif(turn==1):
        print("\nStart of Bot's Turn")
        print(m)
        i,j = botPick()
        print("Computer picks",i+1,j+1)
        m[i,j] = token

    if(hasTwo(m)):
        detGame( (turn +1) % 2, (token +1) % 2 )
    else:
        print("\n end of game\n",m)
        if(np.linalg.det(m)==0):
            if(token==0):
                print(f"Player {turn} wins")
                return turn
            else:
                print(f"Player {(turn+1)%2} wins")
                
                return (turn+1)%2
        else:
            #det = non zero
            if(token==1):
                print(f"Player {turn} wins")
                return turn
            else:
                print(f"Player {(turn+1)%2} wins")
                return (turn+1)%2






def userPick():
    print(f"Pick row (1 to {n})")
    i = int(input())
    print(f"pick column (1 to {n})")
    j = int(input())
    #print('Human coordinates',i,j)
    if( 0<i<n+1 and 0<j<n+1 and m[i-1,j-1]==2 ):
        return i, j
    else:
        print("\nInvalid Choice")
        return userPick()

def botPick():
    i = rng.integers(0,n)
    j = rng.integers(0,n)
    if( m[i,j] != 2):
        return botPick()
    return i, j

def hasTwo(m):
    for x in range(0,n):
        for y in range(0,n):
            if( m[x,y] == 2 ):
                return True
    return False
                 


#case 1: User starts, and can play zero
count = 0
for kk in range(0,1):
    i=detGame(0,0)
    print(i)
    m = 2*np.ones((n,n),int)




Start of user's turn
[[2 2]
 [2 2]]
User picks 2 1

Start of Bot's Turn
[[2 2]
 [0 2]]
Computer picks 2 2

Start of user's turn
[[2 2]
 [0 1]]
User picks 1 1

Start of Bot's Turn
[[0 2]
 [0 1]]
Computer picks 1 2

 end of game
 [[0 1]
 [0 1]]
Player 0 wins
None
